/* AML 인사이트 — 데일리 학습 콘텐츠 (day-of-year 회전)
   확장 방법: 배열에 항목 추가만 하면 됨. 목표 365개. */
const DAILY_EN=[
{e:"The transaction was flagged for further review.",k:"해당 거래는 추가 검토 대상으로 플래그되었다."},
{e:"We filed a suspicious transaction report with the FIU.",k:"우리는 FIU에 의심거래보고를 제출했다."},
{e:"The account was frozen pending investigation.",k:"그 계좌는 조사가 끝날 때까지 동결되었다."},
{e:"Funds were traced through three shell companies.",k:"자금은 세 개의 페이퍼컴퍼니를 거쳐 추적되었다."},
{e:"The customer failed to provide adequate identification.",k:"그 고객은 적절한 신원확인 자료를 제출하지 못했다."},
{e:"Enhanced due diligence applies to high-risk customers.",k:"고위험 고객에게는 강화된 고객확인이 적용된다."},
{e:"The screening system generated a false positive.",k:"스크리닝 시스템이 오탐을 생성했다."},
{e:"We escalated the case to the compliance officer.",k:"우리는 그 건을 준법감시인에게 에스컬레이션했다."},
{e:"The bank was fined for AML control failures.",k:"그 은행은 AML 내부통제 실패로 과태료를 부과받았다."},
{e:"Beneficial ownership must be verified at onboarding.",k:"실제소유자는 거래 개시 시점에 확인되어야 한다."},
{e:"The funds appear to originate from illicit activity.",k:"그 자금은 불법 행위에서 비롯된 것으로 보인다."},
{e:"Structuring involves splitting deposits to avoid thresholds.",k:"분할거래는 기준금액을 회피하기 위해 입금을 쪼개는 것이다."},
{e:"The regulator conducted an on-site examination.",k:"감독당국이 현장검사를 실시했다."},
{e:"We monitor transactions against predefined rules.",k:"우리는 사전 정의된 룰에 따라 거래를 모니터링한다."},
{e:"The alert was cleared after manual review.",k:"그 경보는 수기 검토 후 해제되었다."},
{e:"Sanctions screening is performed in real time.",k:"제재 스크리닝은 실시간으로 수행된다."},
{e:"The customer's risk rating was upgraded to high.",k:"그 고객의 위험등급이 '높음'으로 상향되었다."},
{e:"Records must be retained for five years.",k:"기록은 5년간 보존되어야 한다."},
{e:"The wire transfer lacked originator information.",k:"그 전신송금에는 송금인 정보가 누락되어 있었다."},
{e:"We identified a pattern of rapid pass-through activity.",k:"우리는 급격한 통과거래(패스스루) 패턴을 식별했다."},
{e:"The shell company had no apparent business purpose.",k:"그 페이퍼컴퍼니는 뚜렷한 사업 목적이 없었다."},
{e:"Politically exposed persons require senior management approval.",k:"정치적 주요인물은 고위 경영진의 승인이 필요하다."},
{e:"The audit revealed gaps in transaction monitoring.",k:"감사 결과 거래 모니터링의 공백이 드러났다."},
{e:"Customer due diligence must be refreshed periodically.",k:"고객확인은 주기적으로 갱신되어야 한다."},
{e:"The funds were layered through multiple jurisdictions.",k:"자금은 여러 국가를 거쳐 반복적으로 은닉(레이어링)되었다."},
{e:"We declined the transaction due to sanctions exposure.",k:"제재 위반 가능성 때문에 그 거래를 거절했다."},
{e:"The threshold for cash reporting is set by law.",k:"현금 보고 기준금액은 법으로 정해져 있다."},
{e:"Mule accounts are recruited through job scams.",k:"전달책(대포) 계좌는 구직 사기를 통해 모집된다."},
{e:"The case was closed with no further action.",k:"그 건은 추가 조치 없이 종결되었다."},
{e:"Tipping off a customer is a criminal offense.",k:"고객에게 (조사 사실을) 누설하는 것은 형사처벌 대상이다."},
{e:"The exchange failed to register as a VASP.",k:"그 거래소는 가상자산사업자로 신고하지 못했다."},
{e:"Trade-based laundering exploits over- and under-invoicing.",k:"무역기반 자금세탁은 과다·과소 송장을 악용한다."},
{e:"The risk assessment is reviewed annually.",k:"위험평가는 매년 재검토된다."},
{e:"We requested supporting documents for the transfer.",k:"우리는 그 송금에 대한 증빙서류를 요청했다."},
{e:"The alert volume exceeded our review capacity.",k:"경보량이 우리의 검토 처리 능력을 초과했다."},
{e:"Name matching uses fuzzy logic to catch variants.",k:"이름 대조는 변형 표기를 잡기 위해 퍼지 매칭을 쓴다."},
{e:"The funds were withdrawn immediately after deposit.",k:"그 자금은 입금 직후 곧바로 인출되었다."},
{e:"Internal controls must be independently tested.",k:"내부통제는 독립적으로 검증되어야 한다."},
{e:"The customer refused to explain the source of funds.",k:"그 고객은 자금 출처 설명을 거부했다."},
{e:"We terminated the relationship after repeated red flags.",k:"반복된 위험징후 끝에 우리는 거래관계를 종료했다."},
{e:"The typology involves gift cards converted to crypto.",k:"그 수법은 상품권을 가상자산으로 바꾸는 방식이다."},
{e:"Ongoing monitoring continues throughout the relationship.",k:"지속적 모니터링은 거래관계 내내 계속된다."},
{e:"The report must be filed without delay.",k:"보고는 지체 없이 제출되어야 한다."},
{e:"Correspondent banking carries elevated ML risk.",k:"환거래은행 업무는 높은 자금세탁 위험을 수반한다."},
{e:"The board oversees the AML compliance program.",k:"이사회는 AML 준법 프로그램을 감독한다."},
{e:"We calibrated the rule to reduce false positives.",k:"오탐을 줄이기 위해 룰의 임계값을 조정했다."},
{e:"The investigation uncovered a network of linked accounts.",k:"조사 결과 연결된 계좌들의 네트워크가 드러났다."},
{e:"Source of wealth differs from source of funds.",k:"재산의 원천은 자금의 출처와 다른 개념이다."},
{e:"The license was revoked for repeated violations.",k:"반복된 위반으로 인가가 취소되었다."},
{e:"Smurfing distributes cash across many small deposits.",k:"스머핑은 현금을 다수의 소액 입금으로 분산한다."},
{e:"The remittance was routed through an unlicensed broker.",k:"그 송금은 무허가 중개업자를 통해 이루어졌다."},
{e:"We performed a lookback review of past transactions.",k:"우리는 과거 거래에 대한 소급 검토를 수행했다."},
{e:"The settlement included an independent monitor.",k:"그 합의안에는 독립 감시인 선임이 포함되었다."},
{e:"Red flags alone do not prove money laundering.",k:"위험징후만으로 자금세탁이 입증되는 것은 아니다."},
{e:"The platform enabled anonymous peer-to-peer transfers.",k:"그 플랫폼은 익명 개인 간 이체를 가능하게 했다."},
{e:"Customer risk is scored across multiple factors.",k:"고객위험은 여러 요소에 걸쳐 점수화된다."},
{e:"The funds were commingled with legitimate revenue.",k:"그 자금은 합법적 매출과 뒤섞였다."},
{e:"We documented the rationale for closing the alert.",k:"경보 종결 사유를 문서로 남겼다."},
{e:"The new regulation takes effect next quarter.",k:"새 규정은 다음 분기에 시행된다."},
{e:"Screening lists are updated on a daily basis.",k:"스크리닝 리스트는 매일 갱신된다."},
{e:"The intermediary obscured the ultimate beneficiary.",k:"그 중개자는 최종 수익자를 은폐했다."},
{e:"Failure to report may trigger personal liability.",k:"보고 의무 위반은 개인 책임으로 이어질 수 있다."},
{e:"The model was validated against historical cases.",k:"그 모델은 과거 사례로 검증되었다."},
{e:"Cash-intensive businesses warrant closer scrutiny.",k:"현금 비중이 높은 업종은 더 면밀한 점검이 필요하다."},
{e:"The account showed activity inconsistent with its profile.",k:"그 계좌는 프로필과 일치하지 않는 거래 양상을 보였다."},
{e:"We mapped the flow of funds end to end.",k:"우리는 자금 흐름을 처음부터 끝까지 도식화했다."},
{e:"The exemption applies only to domestic transfers.",k:"그 예외는 국내 이체에만 적용된다."},
{e:"Round-dollar amounts can indicate scripted transfers.",k:"딱 떨어지는 금액은 자동화된 이체의 징후일 수 있다."},
{e:"The compliance program was deemed inadequate.",k:"그 준법 프로그램은 부적정하다고 판정되었다."},
{e:"Proceeds of crime were converted into real estate.",k:"범죄수익이 부동산으로 전환되었다."},
{e:"The hold was released after verification.",k:"확인 절차 후 지급 보류가 해제되었다."},
{e:"We benchmark thresholds against peer institutions.",k:"우리는 동종 기관과 비교해 임계값을 점검한다."},
{e:"The crypto was bridged across chains to break the trail.",k:"그 가상자산은 추적을 끊기 위해 체인 간 브리지를 거쳤다."},
{e:"Each alert must have a documented disposition.",k:"모든 경보에는 문서화된 처리 결과가 있어야 한다."},
{e:"The whistleblower disclosed internal control overrides.",k:"내부고발자가 내부통제 무력화 사실을 폭로했다."},
{e:"Geographic risk is a core component of rating.",k:"국가위험은 위험등급 산정의 핵심 요소다."},
{e:"The funds were repatriated through a loan-back scheme.",k:"그 자금은 대출 가장(loan-back) 방식으로 회수되었다."},
{e:"We tuned the scenario to capture velocity changes.",k:"거래 속도 변화를 포착하도록 시나리오를 조정했다."},
{e:"The fine reflected the duration of the misconduct.",k:"제재금은 위반 기간을 반영해 산정되었다."},
{e:"Standing instructions were used to automate transfers.",k:"자동이체 지시가 이체 자동화에 이용되었다."},
{e:"The review confirmed the customer's stated occupation.",k:"검토 결과 고객이 밝힌 직업이 사실로 확인되었다."},
{e:"Nested accounts hide the true transacting party.",k:"중첩 계좌는 실제 거래 당사자를 숨긴다."},
{e:"The policy requires four-eyes approval for overrides.",k:"그 정책은 예외 처리 시 이중 승인을 요구한다."},
{e:"Adverse media triggered a re-screening of the client.",k:"부정적 언론보도로 그 고객에 대한 재심사가 촉발되었다."},
{e:"The ledger showed circular transfers among affiliates.",k:"원장에는 계열사 간 순환 이체가 나타났다."},
{e:"De-risking pushes customers into informal channels.",k:"위험회피성 거래거절은 고객을 비공식 채널로 내몬다."},
{e:"The task force coordinated across three agencies.",k:"그 합동수사팀은 세 기관에 걸쳐 공조했다."},
{e:"Timely escalation is the analyst's core duty.",k:"적시 보고(에스컬레이션)는 분석가의 핵심 의무다."},
{e:"The evidence established a clear audit trail.",k:"그 증거는 명확한 감사 추적성을 입증했다."}
];
const DAILY_ST=[
{t:"평균 vs 중앙값",d:"극단값이 있으면 평균은 끌려가고 중앙값은 버틴다. 거래금액 분포처럼 한쪽 꼬리가 긴 데이터에선 중앙값이 '보통 고객'을 더 잘 대표한다."},
{t:"표준편차",d:"평균에서 얼마나 흩어져 있는지의 척도. '평소 패턴 대비 몇 σ 벗어났나'가 이상거래 탐지 룰의 출발점이다."},
{t:"Z-점수",d:"(값-평균)/표준편차. 고객별 평소 거래 대비 이번 거래가 얼마나 이례적인지 표준화해 비교할 수 있게 한다."},
{t:"사분위수와 IQR",d:"Q3-Q1 범위 밖 1.5×IQR을 벗어나면 통계적 이상치로 본다. 임계값을 '감'이 아니라 분포로 정하는 가장 쉬운 방법."},
{t:"왜도(Skewness)",d:"분포가 한쪽으로 치우친 정도. 거래금액은 거의 항상 오른쪽 꼬리가 길다 — 평균 기반 룰이 잘 안 먹히는 이유."},
{t:"멱법칙(Power Law)",d:"소수가 대부분을 차지하는 분포. 상위 1% 계좌가 거래대금 대부분을 만든다면, 그 1%에 모니터링을 집중하는 게 합리적이다."},
{t:"조건부확률",d:"P(A|B): B가 일어났을 때 A의 확률. '심야 거래일 때 사기일 확률'처럼 조건을 붙여야 의미 있는 신호가 된다."},
{t:"베이즈 정리",d:"사전확률을 증거로 갱신한다. 기저율(사기 자체가 드묾)을 무시하면 '정확도 99% 모델'도 경보 대부분이 오탐이 된다."},
{t:"기저율의 오류",d:"전체 거래 중 사기가 0.1%면, 오탐률 1%짜리 룰도 경보 10건 중 9건이 정상이다. 정밀도를 따로 봐야 하는 이유."},
{t:"1종 오류(α)",d:"정상을 의심거래로 잘못 잡는 것 = 오탐. 검토 인력을 갉아먹고 고객 불편을 만든다."},
{t:"2종 오류(β)",d:"진짜 의심거래를 놓치는 것 = 미탐. 제재·평판 리스크로 직결된다. α와 β는 트레이드오프 관계다."},
{t:"정밀도(Precision)",d:"경보 중 진짜 비율. 분석가 입장의 체감 품질 — 정밀도 5%면 경보 20건 봐야 1건 건진다."},
{t:"재현율(Recall)",d:"진짜 중 잡아낸 비율. 감독당국 입장의 관심사 — '놓친 게 얼마나 되나'. 정밀도와 함께 봐야 한다."},
{t:"F1 점수",d:"정밀도와 재현율의 조화평균. 룰 튜닝 전후 성능을 한 숫자로 비교할 때 쓴다."},
{t:"ROC 곡선과 AUC",d:"임계값을 바꿔가며 참탐률 vs 오탐률을 그린 곡선. AUC 0.5는 동전 던지기, 1.0은 완벽 — 모델 비교의 표준 언어."},
{t:"임계값 이동의 의미",d:"임계값을 낮추면 재현율↑ 정밀도↓. '얼마에 자를까'는 통계 문제이자 검토 인력·리스크 수용도의 경영 판단이다."},
{t:"p-값",d:"귀무가설이 맞다고 할 때 이만큼 극단적인 데이터가 나올 확률. '우연으로 보기 어렵다'의 정량 표현이지, 효과 크기가 아니다."},
{t:"신뢰구간",d:"추정치의 불확실성 범위. '오탐률 12%'보다 '12%±3%'가 정직한 보고다."},
{t:"표본편향",d:"적발된 사례만 학습하면 '적발하기 쉬운 수법'만 잘 잡는 모델이 된다. STR 데이터의 태생적 한계."},
{t:"생존자 편향",d:"걸러진 것만 보고 전체를 판단하는 오류. '우리 룰에 안 걸렸으니 깨끗하다'는 논리가 위험한 이유."},
{t:"상관 vs 인과",d:"심야 거래와 사기가 상관 있어도 심야가 원인은 아니다. 룰 설명·소명 문서에서 혼동하면 신뢰를 잃는다."},
{t:"심슨의 역설",d:"부분별 경향과 전체 경향이 뒤집히는 현상. 업종별로 나눠 보면 결론이 달라질 수 있다 — 세그먼트 분석이 필수인 이유."},
{t:"이동평균",d:"단기 변동을 눌러 추세를 본다. 고객의 '평소 거래 수준'을 정의할 때 30일 이동평균이 흔한 선택."},
{t:"계절성",d:"월급일·명절·연말정산처럼 주기적 패턴. 이를 모르는 룰은 매달 25일마다 오탐 폭탄을 맞는다."},
{t:"변동계수(CV)",d:"표준편차/평균. 규모가 다른 계좌들의 '들쭉날쭉함'을 공정하게 비교할 수 있게 해준다."},
{t:"포아송 분포",d:"단위시간당 사건 횟수의 분포. '하루 입금 건수가 평소 λ=3인데 오늘 20건'의 이례성을 확률로 말할 수 있다."},
{t:"이항분포",d:"성공/실패 반복의 분포. '100건 중 위험국 송금 비중이 이 정도일 확률'을 계산하는 틀."},
{t:"정규분포와 그 한계",d:"많은 자연현상은 종 모양이지만 금융 데이터는 꼬리가 두껍다. 정규 가정의 룰은 극단 이벤트를 과소평가한다."},
{t:"두꺼운 꼬리(Fat Tail)",d:"극단값이 정규분포 예상보다 훨씬 자주 나오는 분포. 자금세탁은 꼬리에서 일어난다."},
{t:"로그 변환",d:"치우친 금액 데이터에 log를 씌우면 분포가 다루기 쉬워진다. 금액 기반 모델링의 기본 전처리."},
{t:"백분위수 기반 룰",d:"'상위 0.5% 금액'처럼 분포 기준으로 임계값을 정하면 인플레이션·성장에도 룰이 자동 적응한다."},
{t:"허위발견율(FDR)",d:"유의하다고 판정한 것 중 거짓의 비율. 룰 수십 개를 동시에 돌릴 때 '다중검정' 보정이 필요한 이유."},
{t:"대수의 법칙",d:"표본이 커질수록 표본평균이 참값에 다가간다. 한두 달 데이터로 룰 성능을 단정하지 말라는 근거."},
{t:"중심극한정리",d:"표본평균의 분포는 원분포가 무엇이든 정규에 가까워진다. 집계 지표에 통계 검정을 쓸 수 있는 이론적 토대."},
{t:"층화표집",d:"세그먼트별로 나눠 뽑는 표본추출. QA 샘플링에서 고위험군을 과대표집해야 놓침을 점검할 수 있다."},
{t:"회귀분석의 기본",d:"여러 요인이 결과에 미치는 영향을 분리해 본다. '금액 효과'와 '업종 효과'를 떼어내는 도구."},
{t:"로지스틱 회귀",d:"확률(0~1)을 예측하는 회귀. 해석 가능성이 높아 '왜 이 고객이 고위험인가'를 설명해야 하는 AML에 잘 맞는다."},
{t:"오즈비(Odds Ratio)",d:"위험요인이 있을 때 없을 때보다 몇 배 위험한지. '비대면 개설 계좌는 사기 오즈가 3배' 같은 문장의 수학."},
{t:"과적합",d:"학습 데이터의 우연까지 외워버린 모델. 과거 사례엔 완벽한데 새 수법엔 무력해진다 — 검증 데이터 분리가 필수."},
{t:"교차검증",d:"데이터를 나눠 여러 번 학습·검증을 반복. 모델 성능 주장의 최소한의 예의."},
{t:"특이도(Specificity)",d:"정상을 정상이라고 맞게 판정한 비율. 재현율(민감도)과 짝으로 보는 지표."},
{t:"혼동행렬",d:"TP/FP/FN/TN 네 칸 표. 모든 분류 지표의 출발점 — 룰 성과 보고는 이 표 한 장에서 시작하라."},
{t:"리프트(Lift)",d:"모델 상위 구간이 무작위 대비 몇 배 더 잘 잡는지. '상위 10% 경보만 봐도 적발의 60%를 커버' 같은 운영 결정에 쓴다."},
{t:"이상치 탐지 vs 분류",d:"라벨이 없으면 이상치 탐지(비지도), 적발 라벨이 쌓이면 분류(지도)로. AML 모델의 진화 경로다."},
{t:"군집분석",d:"비슷한 거래 패턴끼리 묶는다. '정상 군집에서 멀리 떨어진 계좌'가 새로운 타이폴로지의 후보."},
{t:"그래프의 차수(Degree)",d:"노드에 연결된 엣지 수. 갑자기 수십 계좌와 연결되는 허브 계좌는 집금책의 전형적 신호."},
{t:"매개 중심성",d:"자금 흐름의 길목에 얼마나 자주 서는가. 중계·환치기 계좌 탐지의 그래프 지표."},
{t:"군집계수",d:"내 이웃들끼리도 서로 연결된 정도. 폐쇄적 순환거래 조직은 군집계수가 비정상적으로 높다."},
{t:"연결요소(Component)",d:"서로 도달 가능한 노드 묶음. 사건 하나를 '관련 계좌 전체'로 확장하는 기본 연산."},
{t:"PageRank의 직관",d:"중요한 노드와 연결될수록 중요해진다. 자금 네트워크에서 '진짜 몸통' 계좌를 찾는 데 응용된다."},
{t:"엔트로피",d:"불확실성의 양. 거래 상대가 매번 제각각인 계좌는 거래상대 엔트로피가 높다 — 통과계좌의 신호."},
{t:"지니계수",d:"불평등의 척도. 한 가맹점 매출이 소수 카드에 극단 집중되면 자기결제(허위매출) 의심 신호."},
{t:"벤포드 법칙",d:"자연스러운 숫자의 첫 자리는 1이 약 30%. 조작된 장부·분할거래는 이 분포를 깨는 경우가 많다."},
{t:"체비셰프 부등식",d:"분포를 몰라도 'k표준편차 밖은 최대 1/k²'. 분포 가정 없이 보수적 임계값을 정당화할 때 쓴다."},
{t:"이상거래의 희소성 문제",d:"양성:음성이 1:10000인 데이터에선 정확도(Accuracy)가 무의미하다. '모두 정상'이라 해도 99.99%니까."},
{t:"오버샘플링/언더샘플링",d:"희소한 사기 사례를 부풀리거나 정상을 줄여 학습 균형을 맞추는 기법. SMOTE가 대표적."},
{t:"시계열 분해",d:"추세+계절성+잔차로 쪼개기. '잔차'가 커지는 순간이 진짜 봐야 할 이상 신호다."},
{t:"변화점 탐지",d:"통계적 성질이 바뀌는 시점을 찾는다. 평온하던 계좌가 '다른 계좌'처럼 행동하기 시작한 날 — 명의도용의 흔적."},
{t:"이동 윈도우",d:"최근 N일만 보는 계산 틀. 윈도우가 짧으면 민감하고 길면 둔감하다 — 룰마다 목적에 맞게 골라야 한다."},
{t:"누적합 관리도(CUSUM)",d:"작은 변화가 누적되면 신호를 울리는 기법. 한 건은 미미해도 꾸준한 분할거래를 잡는 데 적합."},
{t:"표본 크기와 검정력",d:"표본이 작으면 진짜 효과도 못 본다. '한 달 파일럿으로 효과 없음'이라는 결론을 경계하라."},
{t:"A/B 테스트",d:"룰 변경 효과를 무작위 배정으로 검증. 임계값 튜닝을 '느낌'에서 '실험'으로 바꾸는 방법."},
{t:"사전등록의 정신",d:"분석 전에 가설과 기준을 못박는다. 결과 보고 기준을 바꾸는 '체리피킹'을 막는 장치."},
{t:"베이지안 갱신의 실무",d:"고객 위험등급은 고정값이 아니라 '증거가 쌓일 때마다 갱신되는 확률'로 보는 게 RBA의 본질이다."},
{t:"사전확률의 출처",d:"국가위험·업종위험 통계가 곧 사전확률이다. 국가위험평가 데이터가 모델의 출발점이 되는 이유."},
{t:"칼리브레이션",d:"'위험 80%'라고 한 것 중 실제 80%가 위험해야 한다. 점수의 크기가 확률로서 믿을 만한가의 문제."},
{t:"PSI(모집단 안정성 지수)",d:"모델 입력 분포가 시간에 따라 얼마나 변했나. 수법이 진화하면 PSI가 먼저 경고한다."},
{t:"개념 드리프트",d:"데이터와 정답의 관계 자체가 변하는 것. 작년에 좋던 모델이 올해 무뎌지는 근본 원인."},
{t:"설명가능성(XAI)의 통계",d:"SHAP 값은 '이 변수 때문에 점수가 +0.3' 식의 기여 분해. 소명·감사 대응에서 블랙박스를 여는 열쇠."},
{t:"가설검정의 두 세계",d:"탐지는 '이상하다'를 찾는 일(탐색), 보고는 '이상하다'를 입증하는 일(확증). 같은 데이터라도 기준이 다르다."},
{t:"상자그림(Boxplot) 읽기",d:"중앙값·사분위·이상치를 한 눈에. 세그먼트별 거래금액 비교 보고서의 가성비 최고 시각화."},
{t:"히스토그램의 함정",d:"구간(빈) 폭에 따라 인상이 달라진다. 임계값 근처 분포를 볼 땐 빈 폭을 바꿔가며 확인하라."},
{t:"산점도와 상관계수",d:"r=0.8이어도 산점도를 봐야 한다 — 이상치 몇 개가 만든 가짜 상관일 수 있다."},
{t:"비율의 비교",d:"'사기율 2% vs 1%'는 2배 차이지만 1%p 차이다. 상대위험과 절대차이를 같이 보고하라."},
{t:"가중평균",d:"규모가 다른 지점들의 지표는 단순평균하면 왜곡된다. 거래량 가중이 기본."},
{t:"중앙값 절대편차(MAD)",d:"이상치에 강한 산포 척도. 극단값 많은 거래 데이터에선 표준편차보다 견고한 기준선이 된다."},
{t:"순위 기반 통계",d:"금액 대신 순위로 보면 극단값 영향이 사라진다. 스피어만 상관이 대표적."},
{t:"부트스트랩",d:"데이터에서 재표집해 불확실성을 추정. 수식 없이도 '오탐률의 신뢰구간'을 구할 수 있다."},
{t:"몬테카를로 직관",d:"무작위 시뮬레이션으로 분포를 그린다. '이 룰이면 하루 경보 몇 건일까'를 배포 전에 가늠하는 도구."},
{t:"마르코프 연쇄의 직관",d:"다음 상태가 현재 상태에만 의존. 고객 상태(정상→주의→고위험) 전이를 모델링하는 틀."},
{t:"희소 이벤트의 추정",d:"0건 관측이 '확률 0'은 아니다. 라플라스 보정(+1)이 작은 표본의 과신을 막는다."},
{t:"동질성 검정(카이제곱)",d:"두 집단의 분포가 같은가. '신규 가맹점군의 업종 분포가 기존과 다른가'를 검정하는 도구."},
{t:"KS 검정",d:"두 분포의 최대 거리로 차이를 본다. 모델 점수가 정상/사기를 얼마나 갈라놓는지의 고전 지표."},
{t:"코호트 분석",d:"가입 시기별로 묶어 추적. '특정 달에 유입된 가맹점군'의 이상 행동을 드러내는 데 강력하다."},
{t:"정상성(Stationarity)",d:"통계적 성질이 시간에 따라 변하지 않는 것. 대부분의 거래 시계열은 비정상 — 차분·변환이 먼저다."},
{t:"자기상관",d:"오늘 값이 어제 값과 닮은 정도. 자기상관 높은 지표에 독립 가정 검정을 쓰면 유의성이 과장된다."},
{t:"이중차분(DID)의 직관",d:"정책 전후×적용/미적용 비교로 효과를 분리. '규제 시행이 거래 패턴을 바꿨나'에 답하는 틀."},
{t:"ROC가 아닌 PR 곡선",d:"극도로 불균형한 데이터에선 ROC가 후해 보인다. 정밀도-재현율 곡선이 AML에 더 정직한 거울."},
{t:"비용 민감 학습",d:"미탐 1건의 비용은 오탐 1건의 수백 배일 수 있다. 손실 함수에 비용을 넣으면 모델의 우선순위가 달라진다."},
{t:"통계적 사고의 본질",d:"숫자는 불확실성과 함께 올 때만 정보다. '몇 건'이 아니라 '평소 대비 얼마나 이례적인가'를 묻는 습관이 분석가를 만든다."}
];
